export enum EventType {
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    FAILED_LOGIN = "FAILED_LOGIN",
    TWO_FACTOR_ENABLED = "TWO_FACTOR_ENABLED",
    TWO_FACTOR_DISABLED = "TWO_FACTOR_DISABLED",

    PASSWORD_RESET = "PASSWORD_RESET",
    PASSWORD_CHANGED = "PASSWORD_CHANGED",
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
    ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED",
    EMAIL_CHANGED = "EMAIL_CHANGED",
    PHONE_CHANGED = "PHONE_CHANGED",

    PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED",
    USERNAME_CHANGED = "USERNAME_CHANGED",
    NOTIFICATION_PREFERENCES_UPDATED = "NOTIFICATION_PREFERENCES_UPDATED",

    ACCOUNT_UPDATE = "ACCOUNT_UPDATE",
    ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
    ACCOUNT_REACTIVATED = "ACCOUNT_REACTIVATED",
    ACCOUNT_DELETED = "ACCOUNT_DELETED",

    NEW_DEVICE_LOGIN = "NEW_DEVICE_LOGIN",
    SESSION_EXPIRED = "SESSION_EXPIRED",
    SESSION_TERMINATED = "SESSION_TERMINATED",
}
